#!/bin/bash

set -e
#set -x

HOME=/app
cd $HOME

## PROFILE
PROFILE=$(dirname $0)/profiles/${1:-mame}
[ ! -f $PROFILE ] && echo "Profile does not exist" && exit 1
source "${PROFILE}"

## SYSTEM settings
MAXTHRD=$(($(nproc)+1))
MINTHRD=$(($MAXTHRD/2))
APPGIT=$HOME/${1:-$APP}
PREFIX=$HOME/output
APPUID=$APPUID
APPGID=$APPGID

## COMPILER
GCC_VER="gcc"
GPP_VER="g++"

### LOGGING
LOGDIR=$HOME/logs/$APP_compile
[ ! -d ${LOGDIR} ] && mkdir -p ${LOGDIR}

## DROPFILE
FAILDROP=$HOME/.buildfail # for containers always returning 0

## MAKE options
MAKEOPT="${MAKEOPT} -j${MAXTHRD} NOWERROR=${NOWERROR}"

#### END OPTS

[ -f $FAILDROP ] && rm -f $FAILDROP

[ ! -f ${APPGIT}/.git/config ] && git clone ${REPO} $APP
cd ${APPGIT}

## GIT safe.directory WORKAROUND
GITARGS="--global"
[ $UID -eq 0 ] && GITARGS="--system"
git config $GITARGS --add safe.directory $HOME/$APP

## GIT operations
git checkout master
git pull
## CHECK version, set latest (this is currently unused)
APPVER=${APPASK:-$(git tag | tail -n1)}

REQFAIL=0
[ -z "${APPVER}" ] && echo "Couldn't set APPVER, intervene" && REQFAIL=1
[ $REQFAIL -ne 0 ] && exit $REQFAIL
git checkout ${APPVER}

# wait here and show version because of sadness
VERMSG="We are going to compile ${APP} version ${APPVER}"
echo -n $VERMSG
sleep 5

log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] ${1}"| tee -a "${2}"
}

drop() {
  touch $FAILDROP
}

perms() {
  chown -R $APPUID:$APPGID $HOME
}

[ $CLEAN -eq 1 ] && make clean 

### COMPILE (with retry counts)
while [ ${TRCNT} -le ${TRIES} ]
do
  FAIL=1
  ## LOGNAME set log name for attempt
  APPLOG="${LOGDIR}/make_${APPVER}_a(${TRCNT})_$(date +'%Y-%m-%d_%H-%M-%S').log"

  log "Compiling with ${MAKEOPT} attempt ${TRCNT}" $APPLOG
  log "gcc Version: $($GCC_VER --version)" ${APPLOG}
  log "CC will be set to $GCC_VER" ${APPLOG}
  log "g++ Version: $($GPP_VER --version)" ${APPLOG}
  log "CXX will be set to $GPP_VER" ${APPLOG}

  ## TEST
  log "BUILD START" $APPLOG

  ## BUILD
  make CC=$GCC_VER CXX=$GPP_VER ${MAKEOPT} CFLAGS="${CFLAGS}" -j ${MAXTHRD} 2>&1 | tee -a ${APPLOG}
  FAIL=$?

  log "BUILD END" $APPLOG
  TRCNT=$(( ${TRCNT} + 1 ))
  ## If compile was successful exit
  if [ $FAIL -eq 0 ] 
  then
    log "BUILD SUCCESS" $APPLOG
    log "INSTALL START" $APPLOG
    install
    log "INSTALL END" $APPLOG
  else
    log "BUILD FAILED" $APPLOG
    drop
  fi
  [ $UID -eq 0 ] && perms
  exit $FAIL
done

